frr defaults traditional
hostname r2
log syslog informational
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip address 10.255.0.2/32
 ip ospf area 0
!
interface eth1
 description link r2-r1 (AS100-AS100)
 ip address 10.0.12.2/24
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 description link r2-r4 (AS100-AS200)
 ip address 10.0.24.2/24
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth3
 description rede de acesso pc2
 ip address 192.168.2.1/24
 ip ospf area 0
 ip ospf passive
!
router ospf
 ospf router-id 10.255.0.2
!
line vty
!
