frr defaults traditional
hostname r4
log syslog informational
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip address 10.255.0.4/32
 ip ospf area 0
!
interface eth1
 description link r4-r2 (AS200-AS100)
 ip address 10.0.24.4/24
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth2
 description link r4-r3 (AS200-AS200)
 ip address 10.0.34.4/24
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth3
 description link r4-r5 (AS200-AS300)
 ip address 10.0.45.4/24
 ip ospf area 0
 ip ospf network point-to-point
!
interface eth4
 description rede de acesso pc4
 ip address 192.168.4.1/24
 ip ospf area 0
 ip ospf passive
!
router ospf
 ospf router-id 10.255.0.4
!
line vty
!
