frr defaults traditional
hostname r3
log syslog informational
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip address 10.255.0.3/32
!
interface eth1
 description link r3-r1 (AS200-AS100)
 ip address 10.0.13.3/24
!
interface eth2
 description link r3-r4 (AS200-AS200)
 ip address 10.0.34.3/24
!
interface eth3
 description link r3-r5 (AS200-AS300)
 ip address 10.0.35.3/24
!
interface eth4
 description rede de acesso pc3
 ip address 192.168.3.1/24
!
router bgp 200
 bgp router-id 10.255.0.3
 no bgp ebgp-requires-policy
 neighbor 10.0.13.1 remote-as 100
 neighbor 10.0.13.1 description eBGP com r1
 neighbor 10.0.34.4 remote-as 200
 neighbor 10.0.34.4 description iBGP com r4
 neighbor 10.0.35.5 remote-as 300
 neighbor 10.0.35.5 description eBGP com r5
 !
 address-family ipv4 unicast
  network 10.255.0.3/32
  network 10.0.13.0/24
  network 10.0.34.0/24
  network 10.0.35.0/24
  network 192.168.3.0/24
  neighbor 10.0.34.4 next-hop-self
 exit-address-family
!
line vty
!
