frr defaults traditional
hostname r4
log syslog informational
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip address 10.255.0.4/32
!
interface eth1
 description link r4-r2 (AS200-AS100)
 ip address 10.0.24.4/24
!
interface eth2
 description link r4-r3 (AS200-AS200)
 ip address 10.0.34.4/24
!
interface eth3
 description link r4-r5 (AS200-AS300)
 ip address 10.0.45.4/24
!
interface eth4
 description rede de acesso pc4
 ip address 192.168.4.1/24
!
router bgp 200
 bgp router-id 10.255.0.4
 no bgp ebgp-requires-policy
 neighbor 10.0.24.2 remote-as 100
 neighbor 10.0.24.2 description eBGP com r2
 neighbor 10.0.34.3 remote-as 200
 neighbor 10.0.34.3 description iBGP com r3
 neighbor 10.0.45.5 remote-as 300
 neighbor 10.0.45.5 description eBGP com r5
 !
 address-family ipv4 unicast
  network 10.255.0.4/32
  network 10.0.24.0/24
  network 10.0.34.0/24
  network 10.0.45.0/24
  network 192.168.4.0/24
  neighbor 10.0.34.3 next-hop-self
 exit-address-family
!
line vty
!
