frr defaults traditional
hostname r5
log syslog informational
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip address 10.255.0.5/32
!
interface eth1
 description link r5-r3 (AS300-AS200)
 ip address 10.0.35.5/24
!
interface eth2
 description link r5-r4 (AS300-AS200)
 ip address 10.0.45.5/24
!
interface eth3
 description rede de acesso pc5
 ip address 192.168.5.1/24
!
router bgp 300
 bgp router-id 10.255.0.5
 no bgp ebgp-requires-policy
 neighbor 10.0.35.3 remote-as 200
 neighbor 10.0.35.3 description eBGP com r3
 neighbor 10.0.45.4 remote-as 200
 neighbor 10.0.45.4 description eBGP com r4
 !
 address-family ipv4 unicast
  network 10.255.0.5/32
  network 10.0.35.0/24
  network 10.0.45.0/24
  network 192.168.5.0/24
 exit-address-family
!
line vty
!
