frr defaults traditional
hostname r2
log syslog informational
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip address 10.255.0.2/32
!
interface eth1
 description link r2-r1 (AS100-AS100)
 ip address 10.0.12.2/24
!
interface eth2
 description link r2-r4 (AS100-AS200)
 ip address 10.0.24.2/24
!
interface eth3
 description rede de acesso pc2
 ip address 192.168.2.1/24
!
router rip
 version 2
 network lo
 network eth1
 network eth2
 network eth3
 passive-interface eth3
!
line vty
!
