frr defaults traditional
hostname r3
log syslog informational
service integrated-vtysh-config
!
ip forwarding
!
interface lo
 ip address 10.255.0.3/32
!
interface eth1
 description link r3-r1 (AS200-AS100)
 ip address 10.0.13.3/24
!
interface eth2
 description link r3-r4 (AS200-AS200)
 ip address 10.0.34.3/24
!
interface eth3
 description link r3-r5 (AS200-AS300)
 ip address 10.0.35.3/24
!
interface eth4
 description rede de acesso pc3
 ip address 192.168.3.1/24
!
router rip
 version 2
 network lo
 network eth1
 network eth2
 network eth3
 network eth4
 passive-interface eth4
!
line vty
!
